baseURL = 'https://shekharsingh1987.github.io/yoga-with-sarya/'
languageCode = 'en-us'
theme = "nightfall"

[menu]
    [[menu.header]]
        name = "about"
        weight = 0
        url = "/about/contact/"
    [[menu.header]]
        name = "posts"
        weight = 0
        url = "/posts"
    

[params]
title = 'Yoga With Sarya'
user = "Sarya"
hostname = "github.io"
sitedescription = 'Welcome to Yoga With Sarya!'
showMetadata = false
published = false
readingTime = false

    [params.author]
    name = "Mrs Sarya"
    email = "sherojdev@gmail.com"

        [[params.social]]
        key = 0
        name = "github"
        url = "https://github.com/gohugoio"
        icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
        target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
        aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO
